#!/usr/bin/env bash
# Usage: script/homebrew
# Release a new version.

set -euo pipefail


read -rp "Enter new version (X.Y.Z): " VERSION
echo "New version: ${VERSION}"
BRIEF_VERSION=${VERSION//./}
echo "Brief version: ${BRIEF_VERSION}"
echo

read -rp "Enter new SHA256: " SHA256
echo "New SHA256: ${SHA256}"
echo

set -v
brew bump-formula-pr --url=https://github.com/sleekbyte/tailor/releases/download/v"${VERSION}"/tailor-"${VERSION}".tar --sha256="${SHA256}" tailor
set +v
